language: java

branches:
  only:
    - master

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script: "ant package-all"

before_script:
 - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa && sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get install ubuntu-sdk
