language: java

branches:
  only:
    - master

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script: "ant package-all"

before_script:
 - pwd
 - git clone https://github.com/mozilla/addon-sdk.git
 - sudo apt-get install click
