language: java

branches:
  only:
    - master

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script: "ant package-all"

before_script:
 - wget https://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/jetpack-sdk-latest.tar.gz
 - tar -xf addon-sdk.tar.gz
 - sudo apt-get install click
